const wordData = [
  { category: "Animals", word: "elephant", length: 8 },
  { category: "Animals", word: "giraffe", length: 7 },
  { category: "Animals", word: "tiger", length: 5 },
  { category: "Animals", word: "monkey", length: 6 },
  { category: "Animals", word: "snake", length: 5 },
  { category: "Animals", word: "penguin", length: 7 },
  { category: "Animals", word: "koala", length: 5 },
  { category: "Animals", word: "kangaroo", length: 8 },
  { category: "Animals", word: "panda", length: 5 },
  { category: "Animals", word: "hippopotamus", length: 12 },

  { category: "Fruits", word: "apple", length: 5 },
  { category: "Fruits", word: "banana", length: 6 },
  { category: "Fruits", word: "orange", length: 6 },
  { category: "Fruits", word: "strawberry", length: 10 },
  { category: "Fruits", word: "grape", length: 5 },
  { category: "Fruits", word: "watermelon", length: 10 },
  { category: "Fruits", word: "pineapple", length: 9 },
  { category: "Fruits", word: "kiwi", length: 4 },
  { category: "Fruits", word: "pear", length: 4 },
  { category: "Fruits", word: "peach", length: 5 },

  { category: "Countries", word: "USA", length: 3 },
  { category: "Countries", word: "China", length: 5 },
  { category: "Countries", word: "India", length: 5 },
  { category: "Countries", word: "Brazil", length: 6 },
  { category: "Countries", word: "Russia", length: 6 },
  { category: "Countries", word: "Japan", length: 5 },
  { category: "Countries", word: "Germany", length: 7 },
  { category: "Countries", word: "France", length: 6 },
  { category: "Countries", word: "UK", length: 2 },
  { category: "Countries", word: "Italy", length: 5 },

  { category: "Colors", word: "red", length: 3 },
  { category: "Colors", word: "blue", length: 4 },
  { category: "Colors", word: "green", length: 5 },
  { category: "Colors", word: "yellow", length: 6 },
  { category: "Colors", word: "orange", length: 6 },
  { category: "Colors", word: "purple", length: 6 },
  { category: "Colors", word: "black", length: 5 },
  { category: "Colors", word: "white", length: 5 },
  { category: "Colors", word: "brown", length: 5 },
  { category: "Colors", word: "pink", length: 4 },

  { category: "Professions", word: "doctor", length: 6 },
  { category: "Professions", word: "teacher", length: 7 },
  { category: "Professions", word: "engineer", length: 8 },
  { category: "Professions", word: "artist", length: 6 },
  { category: "Professions", word: "chef", length: 4 },
  { category: "Professions", word: "police", length: 6 },
  { category: "Professions", word: "firefighter", length: 11 },
  { category: "Professions", word: "lawyer", length: 6 },
  { category: "Professions", word: "scientist", length: 9 },
  { category: "Professions", word: "writer", length: 6 },

  { category: "Sports", word: "soccer", length: 6 },
  { category: "Sports", word: "basketball", length: 10 },
  { category: "Sports", word: "football", length: 8 },
  { category: "Sports", word: "tennis", length: 6 },
  { category: "Sports", word: "golf", length: 4 },
  { category: "Sports", word: "swimming", length: 8 },
  { category: "Sports", word: "volleyball", length: 10 },
  { category: "Sports", word: "boxing", length: 6 },
  { category: "Sports", word: "cricket", length: 7 },
  { category: "Sports", word: "rugby", length: 5 },

  { category: "Planets", word: "mercury", length: 7 },
  { category: "Planets", word: "venus", length: 5 },
  { category: "Planets", word: "earth", length: 5 },
  { category: "Planets", word: "mars", length: 4 },
  { category: "Planets", word: "jupiter", length: 7 },
  { category: "Planets", word: "saturn", length: 6 },
  { category: "Planets", word: "uranus", length: 6 },
  { category: "Planets", word: "neptune", length: 7 },
  { category: "Planets", word: "pluto", length: 5 },
  { category: "Planets", word: "moon", length: 4 },

  { category: "Transportation", word: "car", length: 3 },
  { category: "Transportation", word: "train", length: 5 },
  { category: "Transportation", word: "bicycle", length: 7 },
  { category: "Transportation", word: "bus", length: 3 },
  { category: "Transportation", word: "airplane", length: 8 },
  { category: "Transportation", word: "boat", length: 4 },
  { category: "Transportation", word: "motorcycle", length: 10 },
  { category: "Transportation", word: "subway", length: 6 },
  { category: "Transportation", word: "helicopter", length: 10 },
  { category: "Transportation", word: "truck", length: 5 },

  { category: "Body Parts", word: "head", length: 4 },
  { category: "Body Parts", word: "arm", length: 3 },
  { category: "Body Parts", word: "leg", length: 3 },
  { category: "Body Parts", word: "hand", length: 4 },
  { category: "Body Parts", word: "foot", length: 4 },
  { category: "Body Parts", word: "eye", length: 3 },
  { category: "Body Parts", word: "ear", length: 3 },
  { category: "Body Parts", word: "nose", length: 4 },
  { category: "Body Parts", word: "mouth", length: 5 },
  { category: "Body Parts", word: "back", length: 4 },

  { category: "Weather", word: "sunny", length: 5 },
  { category: "Weather", word: "rainy", length: 5 },
  { category: "Weather", word: "cloudy", length: 6 },
  { category: "Weather", word: "windy", length: 5 },
  { category: "Weather", word: "stormy", length: 6 },
  { category: "Weather", word: "snowy", length: 5 },
  { category: "Weather", word: "foggy", length: 5 },
  { category: "Weather", word: "hot", length: 3 },
  { category: "Weather", word: "cold", length: 4 },
  { category: "Weather", word: "humid", length: 5 },

  { category: "Shapes", word: "circle", length: 6 },
  { category: "Shapes", word: "square", length: 6 },
  { category: "Shapes", word: "triangle", length: 8 },
  { category: "Shapes", word: "rectangle", length: 9 },
  { category: "Shapes", word: "pentagon", length: 8 },
];

export default wordData;
